### ISSUE TITLE
Clarification of readme

### ISSUE THREAD

**Issue by kjelljorner** [JacksonBurns/py2sambvca#20]
Regarding the readme text, I want to clarify that I'm not using py2sambvca for anything in [morfeus](https://github.com/kjelljorner/morfeus). I have mainly used your tool to benchmark against the original Fortran BV code. Morfeus has it's own, independent implementation of BV. Indeed the license prevented me from using Sambvca at the time. Also, morfeus is a much broader tool than for "Phosphine ligand parameterization", it can calculate features for a range of different molecules. 

```
Examples

Here are a couple repositories using py2sambvca as a Python package or extending its source code, check them out:

[Metal-organic framework stability analysis by Hiu Ki](https://github.com/hiukiwong/mof-stability-ml)
[Phosphine ligand parameterization for Machine Learning by Kjell Jorner](https://github.com/kjelljorner/morfeus)
[MOF Stability ML by Ruihan Wang](https://github.com/ruihwang/mof-stability-ml)
```

**Comment by JacksonBurns** [comment]
I've opened and linked a PR to clarify this point - mind giving it a look?
