### ISSUE TITLE
Clarifications on conditions for use

### ISSUE THREAD

**Issue by kjelljorner** [JacksonBurns/py2sambvca#4]
Since you package the original Fortran source code with the repo, it would be good to make clear that:

1. It cannot be used for industrial or commercial use without agreement from the original authors
2. The original authors must be acknowledged for results obtained.

Otherwise users that only come across this package but don't go to check the original license conditions might miss that. The first condition is actually why I developed my own algorithm in Morfeus as I was not able to use SambVca at the time.

**Comment by JacksonBurns** [comment]
Thanks for that note! I will update the README with these points.

**Comment by JacksonBurns** [comment]
resolved with 2eb14bb6f0c5c63e2121f0f1e36cbac5a86db278
